<a href="https://colab.research.google.com/github/Qianq0625/Learnning-Knowledge/blob/main/v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.arange(12)
x 

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x.numel() #number of elements in tensor

12

In [ ]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
torch.zeros((4,3,5)) #ones

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,4,1])
x**y #power operations
torch.exp(x) #Exponential operations

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [ ]:
x = torch.arange(12,dtype = torch.float32).reshape((3,4))
x

y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
y

torch.cat((x,y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [ ]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
x.sum()

tensor(66.)

In [ ]:
#broadcasting mechanism
a = torch.arange(12).reshape((3,2,2))
b = torch.arange(4).reshape((1,2,2))
a,b

(tensor([[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]],
 
         [[ 8,  9],
          [10, 11]]]), tensor([[[0, 1],
          [2, 3]]]))

In [ ]:
a+b

tensor([[[ 0,  2],
         [ 4,  6]],

        [[ 4,  6],
         [ 8, 10]],

        [[ 8, 10],
         [12, 14]]])

In [ ]:
before = id(y)
before
y = y + x
id(y)
id(y) == before

False

In [ ]:
z = torch.zeros_like(y)
before = id(z)

z[:] = x + y
id(z)
print("id(z):", id(z) == before)

# use x[:]= x+y or x += y to reduce the storge 

id(z): True


In [ ]:
a = torch.tensor([2])
a
a.item()

# only one element tensors can be converted to python scalars

2

In [ ]:
import os  #libraray about operation system

os.makedirs(os.path.join('..','content'),exist_ok = True)
data_file = os.path.join('..','content','house_tiny.csv')
with open(data_file, 'w') as f:
  f.write('NumRooms,Alley,Price\n')
  f.write('NA,Pave,127500\n')
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')

In [ ]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [ ]:
inputs,outputs = data.iloc[:, 0:2], data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())
print(inputs)
print(outputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64


<ipython-input-5-56f9fd974209>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [ ]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

#pd.from_dummies(inputs, sep = "_")

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [ ]:
import torch

a = torch.arange(12)
a
b = a.reshape((3,4)) # couldn't change the address
b

b[:] = 2
b

a #also will be changed

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])