<a href="https://colab.research.google.com/github/Qianq0625/Learnning-Knowledge/blob/main/V2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

x = torch.arange(4.0)
x

#save gradiants
x.requires_grad_(True)
x.grad

print(x.grad)

None


In [7]:
x = torch.arange(4.0,requires_grad=True)
print(x.grad)

None


In [8]:
y = 2 * torch.dot(x,x)  #dot product
y

tensor(28., grad_fn=<MulBackward0>)

In [10]:
#x.grad.zero_()
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [76]:
x.grad == 4 * x

tensor([True, True, True, True])

In [80]:
x.grad.zero_() # pytorch will accumulate gradients, so we need to clear the previous values
x #0,1,2,3
y = x.sum() #!Decisive!
y #6

y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [25]:
# 在 y.backward() 时，如果 y 是标量，则不需要为 backward() 传入任何参数；否则，需要传入一个与 y 同形的Tensor。

x.grad.zero_()
y = x * x
y

#y.backward(torch.ones(len(x)))
#y
x.grad

y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [65]:
#把网络中一些参数固定住，这是很有用的功能
x.grad.zero_()
y = x * x  #tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)
u = y.detach() #tensor([0., 1., 4., 9.]) 防止参数回传
z = u * x

print(x)
print(y)
print(u)
print(z)

#z.backward(torch.ones(len(x)))
result = z.sum().backward()
print(result)
print(z)
x.grad == u

tensor([0., 1., 2., 3.], requires_grad=True)
tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)
tensor([0., 1., 4., 9.])
tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)
None
tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)


tensor([True, True, True, True])

In [66]:
x.grad.zero_()
y.backward(torch.ones(len(x)))
#y.sum().backward()
print(y)
x.grad == 2 * x

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


tensor([True, True, True, True])

In [72]:
def f(a):
  b = a * 2
  while b.norm() < 1000:
    b = b * 2
  if b.sum() > 0:
    c = b
  else:
    c = 100 * b
  return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
print(a)
print(d)
print(d/a)
a.grad == d/a
#print(a.grad)

tensor(1.6760, requires_grad=True)
tensor(1716.1744, grad_fn=<MulBackward0>)
tensor(1024., grad_fn=<DivBackward0>)
tensor(1024.)
